//
//  CLH-Define.h
//  FangChuang
//
//  Created by chenlihua on 14-9-17.
//  Copyright (c) 2014年 蓝色互动. All rights reserved.
//

#ifndef FangChuang_CLH_Define_h
#define FangChuang_CLH_Define_h

//筛选部分default
//选择的内容
#define CLH_DEFAULT_SEARCH_CURRENCY   @"CLH_DEFAULT_SEARCH_CURRENCY"
#define CLH_DEFAULT_SEARCH_TURN   @"CLH_DEFAULT_SEARCH_TURN"
#define CLH_DEFAULT_SEARCH_STAGE    @"CLH_DEFAULT_SEARCH_STAGE"
#define CLH_DEFAULT_SEARCH_BUSINESS @"CLH_DEFAULT_SEARCH_BUSINESS"
#define CLH_DEFAULT_SEARCH_MONEY   @"CLH_DEFAULT_SEARCH_MONEY"
#define CLH_DEFAULT_SEARCH_INDEX   @"CLH_DEFAULT_SEARCH_INDEX"

#define CLH_DEFAULT_SEARCH_INDEX_BUSINESS  @"CLH_DEFAULT_SEARCH_INDEX_BUSINESS"
#define CLH_DEFAULT_SEARCH_INDEX_CURRENCY   @"CLH_DEFAULT_SEARCH_INDEX_CURRENCY"
#define CLH_DEFAULT_SEARCH_INDEX_MONEY   @"CLH_DEFAULT_SEARCH_INDEX_MONEY"
#define CLH_DEFAULT_SEARCH_INDEX_STATE   @"CLH_DEFAULT_SEARCH_INDEX_STATE"
#define CLH_DEFAULT_SEARCH_INDEX_TURN   @"CLH_DEFAULT_SEARCH_INDEX_TURN"

//融资进程，新增机构中
#define CLH_DEFAULT_FINANCE_STATE @"CLH_DEFAULT_FINANCE_STATE"
#define CLH_DEFAULT_FINANCE_GROUP @"CLH_DEFAULT_FINANCE_GROUP"
#define CLH_DEFAULT_FINANCE_ADD_FLAG @"CLH_DEFAULT_FINANCE_ADD_FLAG"

#define CLH_DEFAULT_FINANCE_STATE_INDEX @"CLH_DEFAULT_FINANCE_STATE_INDEX "
#define CLH_DEFAULT_FINANCE_GROUP_INDEX  @"CLH_DEFAULT_FINANCE_GROUP_INDEX "
#define CLH_DEFAULT_FINANCE_ADD_FLAG_INDEX  @"CLH_DEFAULT_FINANCE_ADD_FLAG_INDEX "


//融资进程点击详细页面进去
#define CLH_DEFAULT_FINANCE_DETAIL_STATE @"CLH_DEFAULT_FINANCE_DETAIL_STATE"
#define CLH_DEFAULT_FINANCE_DETAIL_GROUP @"CLH_DEFAULT_FINANCE_DETAIL_GROUP"
#define CLH_DEFAULT_FINANCE_DETAIL_ADD_FLAG @"CLH_DEFAULT_FINANCE_DETAIL_ADD_FLAG"

//公司标签添加，基本信息中状态，组别的跳转标志
#define CLH_NSSTRING_FINANCE_RIGHT_ADD_COMPANY_FLAG  @"CLH_NSSTRING_FINANCE_RIGHT_ADD_COMPANY_FLAG"
#define CLH_NSSTRING_FINANCE_RIGHT_ADD_STATE_FLAG  @"CLH_NSSTRING_FINANCE_RIGHT_ADD_STATE_FLAG"
#define CLH_NSSTRING_FINANCE_RIGHT_ADD_GROUP_FLAG  @"CLH_NSSTRING_FINANCE_RIGHT_ADD_GROUP_FLAG"

#define CLH_NSSTRING_FINANCE_DETAIL_ADD_COMPANY_FLAG  @"CLH_NSSTRING_FINANCE_DETAIL_ADD_COMPANY_FLAG"
#define CLH_NSSTRING_FINANCE_DETAIL_ADD_STATE_FLAG  @"CLH_NSSTRING_FINANCE_DETAIL_ADD_STATE_FLAG"
#define CLH_NSSTRING_FINANCE_DETAIL_ADD_GROUP_FLAG  @"CLH_NSSTRING_FINANCE_DETAIL_ADD_GROUP_FLAG"

//电书书
#define recordUrl  @"http://fcapp.favalue.com/data/upload/1/201402/27/2718033203432a6d.pdf"

//跟进信息跳转标志
#define CLH_NSSTRING_FINANCE_DETAIL_CELL @"CLH_NSSTRING_FINANCE_DETAIL_CELL"
#define CLH_NSSTRING_FINANCE_ADD_STATE_GROUP @"CLH_NSSTRING_FINANCE_ADD_STATE_GROUP"

//筛选页面跳转
#define CLH_NSSTRING_PROJECT_RIGHT_SEARCH_VIEW @"CLH_NSSTRING_PROJECT_RIGHT_SEARCH_VIEW "
#define CLH_NSSTRING_PRPJECT_RIGHT_SEARCH_DETAIL_VIEW @"CLH_NSSTRING_PRPJECT_RIGHT_SEARCH_DETAIL_VIEW"

//融资进程，新增机构.机构名称，联系人，见面次数，Ps的本地保存
#define CLH_DEFAULT_FINANCE_RIGHT_ADD_NAME @"CLH_DEFAULT_FINANCE_RIGHT_ADD_NAME"
#define CLH_DEFAULT_FINANCE_RIGHT_ADD_CONTRACT @"CLH_DEFAULT_FINANCE_RIGHT_ADD_CONTRACT"
#define CLH_DEFAULT_FINANCE_RIGHT_ADD_MEET @"CLH_DEFAULT_FINANCE_RIGHT_ADD_MEET"
#define CLH_DEFAULT_FINANCE_RIGHT_ADD_PS @"CLH_DEFAULT_FINANCE_RIGHT_ADD_PS"

//跟进信息，编辑界面
#define CLH_DEFAULT_FINANCE_DETAIL_ADD_CONTRACT @"CLH_DEFAULT_FINANCE_DETAIL_ADD_CONTRACT"
#define CLH_DEFAULT_FINANCE_DETAIL_ADD_MEET @"CLH_DEFAULT_FINANCE_DETAIL_ADD_MEET"
#define CLH_DEFAULT_FINANCE_DETAIL_ADD_PS @"CLH_DEFAULT_FINANCE_DETAIL_ADD_PS"


//创业者跳转标志
#define CLH_NSSTRING_HOME_ENTRE_DETAIL @"CLH_NSSTRING_HOME_ENTRE_DETAIL"

//创业者部分选择的内容
#define CLH_DEFAULT_ENTRE_SCALE   @"CLH_DEFAULT_ENTRE_SCALE"
#define CLH_DEFAULT_ENTRE_MONEY   @"CLH_DEFAULT_ENTRE_MONEY"
#define CLH_DEFAULT_ENTRE_STAGE   @"CLH_DEFAULT_ENTRE_STAGE "
#define CLH_DEFAULT_ENTRE_BUSINESS @"CLH_DEFAULT_ENTRE_BUSINESS"

//投资者跳转标志
#define CLH_NSSTRING_HOME_INVEST_DETAIL @"CLH_NSSTRING_HOME_INVEST_DETAIL"

//投资者部分选择的内容
#define CLH_DEFAULT_INVEST_CURRENCY   @"CLH_DEFAULT_INVEST_CURRENCY"
#define CLH_DEFAULT_INVEST_MONEY   @"CLH_DEFAULT_INVEST_MONEY"
#define CLH_DEFAULT_INVEST_TURN   @"CLH_DEFAULT_INVEST_TURN "
#define CLH_DEFAULT_INVEST_BUSINESS @"CLH_DEFAULT_INVEST_BUSINESS"


#endif
